name: Publish CocoaPods
defaults:
  run:
    shell: bash -eo pipefail {0}
on:
  release:
    types: [published]

jobs:
  publish:
    strategy:
      matrix:
        os: [macOS-13]
        xcode: ['15.0']

    name: Publish CocoaPods
    runs-on: ${{ matrix.os }}
    env:
      LOGSDIR: /tmp/.cborcoding.cocoapods/Logs
      COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}

    steps:
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}

    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup CocoaPods
      uses: maxim-lobanov/setup-cocoapods@v1
      with:
        version: latest

    - name: Setup Environment
      run: |
        mkdir -p "$LOGSDIR"

    - name: Publish CocoaPod
      run: |
        pod trunk push CBORCoding.podspec --verbose 2>&1 | tee "$LOGSDIR/CocoaPods.log"

    - name: Upload Logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Logs
        path: ${{ env.LOGSDIR }}/*.log
