name: Swift Package
on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]

    name: Build
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build
      run: |
        swift --version
        swift build -v

  test:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]

    name: Test
    runs-on: ${{ matrix.os }}
    needs: build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Test
      run: |
        swift test -v --enable-code-coverage

    - name: Generate Code Coverage File
      if: ${{ runner.os == 'macOS' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: |
        xcrun llvm-cov export --instr-profile=.build/x86_64-apple-macosx/debug/codecov/default.profdata .build/x86_64-apple-macosx/debug/CBORCodingPackageTests.xctest/Contents/MacOS/CBORCodingPackageTests > ./info.lcov

    - name: Upload Code Coverage
      if: ${{ runner.os == 'macOS' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./info.lcov
        verbose: true
